version: '3.8'

services:
  database:
    build:
      context: ./database/
      dockerfile: Dockerfile
    image: database
    container_name: fe
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - midterm

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: backend
    container_name: be
    depends_on:
      - database
    environment:
      - MONGO_URL=mongodb://database:27017
    ports:
      - "8000:8000"
    networks:
      - midterm

  front-end:
    build:
      context: ./front-end/
      dockerfile: Dockerfile
    image: frontend
    container_name: db
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - midterm
    environment:
      - REACT_APP_API_URL=http://backend:8000

volumes:
  mongo_data:

networks:
  midterm:
